import { useState, useEffect } from 'react';
import { X, Calendar as CalendarIcon, Clock, User, Video, MapPin, Phone, Copy, Check, Loader2, Mail } from 'lucide-react';
import { scheduleInterview } from '../../utils/api';

interface CalendarModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function CalendarModal({ isOpen, onClose }: CalendarModalProps) {
  const [candidateName, setCandidateName] = useState('');
  const [candidateEmail, setCandidateEmail] = useState('');
  const [startTime, setStartTime] = useState('');
  const [endTime, setEndTime] = useState('');
  const [interviewType, setInterviewType] = useState<'video' | 'in-person' | 'phone'>('video');
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [location, setLocation] = useState('');
  const [isScheduling, setIsScheduling] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [scheduledInterview, setScheduledInterview] = useState<any>(null);
  const [copiedLink, setCopiedLink] = useState(false);

  useEffect(() => {
    if (!isOpen) {
      // Reset state when modal closes
      setCandidateName('');
      setCandidateEmail('');
      setStartTime('');
      setEndTime('');
      setTitle('');
      setDescription('');
      setLocation('');
      setScheduledInterview(null);
      setError(null);
      setInterviewType('video');
    }
  }, [isOpen]);

  const handleSchedule = async () => {
    if (!candidateName.trim()) {
      setError('Please enter candidate name');
      return;
    }
    if (!candidateEmail.trim()) {
      setError('Please enter candidate email');
      return;
    }
    if (!startTime) {
      setError('Please select start time');
      return;
    }
    if (!endTime) {
      setError('Please select end time');
      return;
    }

    // Validate that end time is after start time
    const start = new Date(startTime);
    const end = new Date(endTime);
    if (start >= end) {
      setError('End time must be after start time');
      return;
    }
    if (start < new Date()) {
      setError('Cannot schedule interview in the past');
      return;
    }

    setIsScheduling(true);
    setError(null);

    try {
      // Generate meeting link (will be auto-generated by backend if not provided)
      const meetingLink = `https://meet.company.com/interview/${Date.now()}-${Math.random().toString(36).substring(2, 8)}`;

      const response = await scheduleInterview({
        candidateEmail: candidateEmail.trim(),
        candidateName: candidateName.trim(),
        startTime: start.toISOString(),
        endTime: end.toISOString(),
        title: title || `Interview - ${candidateName} - Python Developer Position`,
        description: description || `Interview with ${candidateName} for Python Developer position`,
        interviewType,
        location: interviewType === 'in-person' ? location : undefined,
        meetingLink,
        interviewerEmail: 'sarah.chen@company.com',
        interviewerName: 'Sarah Chen (HR Manager)',
      });

      setScheduledInterview(response.interview);
    } catch (err: any) {
      console.error('Schedule error:', err);
      setError(err.message || 'Failed to schedule interview');
    } finally {
      setIsScheduling(false);
    }
  };

  const handleCopyLink = () => {
    if (scheduledInterview?.meetingLink) {
      navigator.clipboard.writeText(scheduledInterview.meetingLink);
      setCopiedLink(true);
      setTimeout(() => setCopiedLink(false), 2000);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-[12px] w-full max-w-2xl max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="sticky top-0 bg-white border-b border-[#E5E5E5] px-6 py-4 flex items-center justify-between z-10">
          <div className="flex items-center gap-3">
            <CalendarIcon className="w-6 h-6 text-[#6366F1]" />
            <h2 className="text-[20px] font-semibold text-[#0D0D0D]">Schedule Meeting</h2>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-[#FAFAFA] rounded-[6px] transition-colors"
          >
            <X className="w-5 h-5 text-[#787878]" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6">
          {scheduledInterview ? (
            /* Success View - Show Meeting Link */
            <div className="space-y-4">
              <div className="bg-[#D1FAE5] border border-[#059669] rounded-[8px] p-4">
                <div className="flex items-center gap-2 mb-2">
                  <Check className="w-5 h-5 text-[#059669]" />
                  <h3 className="text-[16px] font-semibold text-[#059669]">Meeting Scheduled Successfully!</h3>
                </div>
                <div className="space-y-2 text-[14px] text-[#0D0D0D]">
                  <p><strong>Candidate:</strong> {scheduledInterview.candidateName}</p>
                  <p><strong>Date & Time:</strong> {new Date(scheduledInterview.startTime).toLocaleString()}</p>
                  <p><strong>Duration:</strong> {scheduledInterview.duration} minutes</p>
                </div>
              </div>

              {/* Meeting Link Section */}
              <div className="border border-[#E5E5E5] rounded-[8px] p-4">
                <label className="block text-[14px] font-medium text-[#0D0D0D] mb-2">
                  Meeting Link
                </label>
                <div className="flex items-center gap-2">
                  <input
                    type="text"
                    value={scheduledInterview.meetingLink}
                    readOnly
                    className="flex-1 px-3 py-2 bg-[#FAFAFA] border border-[#E5E5E5] rounded-[6px] text-[14px] text-[#0D0D0D]"
                  />
                  <button
                    onClick={handleCopyLink}
                    className="px-4 py-2 bg-[#6366F1] text-white rounded-[6px] text-[14px] font-medium hover:bg-[#4F46E5] transition-colors flex items-center gap-2"
                  >
                    {copiedLink ? (
                      <>
                        <Check className="w-4 h-4" />
                        <span>Copied!</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-4 h-4" />
                        <span>Copy</span>
                      </>
                    )}
                  </button>
                </div>
                <p className="text-[12px] text-[#787878] mt-2">
                  Copy this link to share with the candidate via email
                </p>
              </div>

              <div className="flex gap-3">
                <button
                  onClick={onClose}
                  className="flex-1 px-4 py-2.5 bg-[#6366F1] text-white rounded-[6px] text-[14px] font-medium hover:bg-[#4F46E5] transition-colors"
                >
                  Done
                </button>
                <button
                  onClick={() => {
                    setScheduledInterview(null);
                    setCandidateName('');
                    setCandidateEmail('');
                    setStartTime('');
                    setEndTime('');
                    setTitle('');
                    setDescription('');
                    setLocation('');
                  }}
                  className="px-4 py-2.5 bg-white border border-[#E5E5E5] text-[#0D0D0D] rounded-[6px] text-[14px] font-medium hover:bg-[#FAFAFA] transition-colors"
                >
                  Schedule Another
                </button>
              </div>
            </div>
          ) : (
            /* Schedule Form */
            <div className="space-y-4">
              {error && (
                <div className="bg-[#FEE2E2] border border-[#DC2626] rounded-[8px] p-3">
                  <p className="text-[14px] text-[#DC2626]">{error}</p>
                </div>
              )}

              {/* Candidate Name */}
              <div>
                <label className="block text-[14px] font-medium text-[#0D0D0D] mb-2">
                  Candidate Name <span className="text-[#DC2626]">*</span>
                </label>
                <input
                  type="text"
                  value={candidateName}
                  onChange={(e) => setCandidateName(e.target.value)}
                  placeholder="Enter candidate name"
                  className="w-full px-4 py-2.5 border border-[#E5E5E5] rounded-[6px] text-[14px] text-[#0D0D0D] focus:outline-none focus:ring-2 focus:ring-[#6366F1]"
                />
              </div>

              {/* Candidate Email */}
              <div>
                <label className="block text-[14px] font-medium text-[#0D0D0D] mb-2">
                  Candidate Email <span className="text-[#DC2626]">*</span>
                </label>
                <input
                  type="email"
                  value={candidateEmail}
                  onChange={(e) => setCandidateEmail(e.target.value)}
                  placeholder="candidate@example.com"
                  className="w-full px-4 py-2.5 border border-[#E5E5E5] rounded-[6px] text-[14px] text-[#0D0D0D] focus:outline-none focus:ring-2 focus:ring-[#6366F1]"
                />
              </div>

              {/* Start Time */}
              <div>
                <label className="block text-[14px] font-medium text-[#0D0D0D] mb-2">
                  Start Time <span className="text-[#DC2626]">*</span>
                </label>
                <input
                  type="datetime-local"
                  value={startTime}
                  onChange={(e) => setStartTime(e.target.value)}
                  min={new Date().toISOString().slice(0, 16)}
                  className="w-full px-4 py-2.5 border border-[#E5E5E5] rounded-[6px] text-[14px] text-[#0D0D0D] focus:outline-none focus:ring-2 focus:ring-[#6366F1]"
                />
              </div>

              {/* End Time */}
              <div>
                <label className="block text-[14px] font-medium text-[#0D0D0D] mb-2">
                  End Time <span className="text-[#DC2626]">*</span>
                </label>
                <input
                  type="datetime-local"
                  value={endTime}
                  onChange={(e) => setEndTime(e.target.value)}
                  min={startTime || new Date().toISOString().slice(0, 16)}
                  className="w-full px-4 py-2.5 border border-[#E5E5E5] rounded-[6px] text-[14px] text-[#0D0D0D] focus:outline-none focus:ring-2 focus:ring-[#6366F1]"
                />
              </div>

              {/* Interview Type */}
              <div>
                <label className="block text-[14px] font-medium text-[#0D0D0D] mb-2">
                  Interview Type <span className="text-[#DC2626]">*</span>
                </label>
                <select
                  value={interviewType}
                  onChange={(e) => setInterviewType(e.target.value as any)}
                  className="w-full px-4 py-2.5 border border-[#E5E5E5] rounded-[6px] text-[14px] text-[#0D0D0D] focus:outline-none focus:ring-2 focus:ring-[#6366F1]"
                >
                  <option value="video">Video Call</option>
                  <option value="in-person">In-Person</option>
                  <option value="phone">Phone Call</option>
                </select>
              </div>

              {/* Location (for in-person) */}
              {interviewType === 'in-person' && (
                <div>
                  <label className="block text-[14px] font-medium text-[#0D0D0D] mb-2">
                    Location
                  </label>
                  <input
                    type="text"
                    value={location}
                    onChange={(e) => setLocation(e.target.value)}
                    placeholder="Office address or room number"
                    className="w-full px-4 py-2.5 border border-[#E5E5E5] rounded-[6px] text-[14px] text-[#0D0D0D] focus:outline-none focus:ring-2 focus:ring-[#6366F1]"
                  />
                </div>
              )}

              {/* Title */}
              <div>
                <label className="block text-[14px] font-medium text-[#0D0D0D] mb-2">
                  Title (Optional)
                </label>
                <input
                  type="text"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="e.g., Technical Interview - Python Developer"
                  className="w-full px-4 py-2.5 border border-[#E5E5E5] rounded-[6px] text-[14px] text-[#0D0D0D] focus:outline-none focus:ring-2 focus:ring-[#6366F1]"
                />
              </div>

              {/* Description */}
              <div>
                <label className="block text-[14px] font-medium text-[#0D0D0D] mb-2">
                  Description (Optional)
                </label>
                <textarea
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="Add meeting description..."
                  rows={3}
                  className="w-full px-4 py-2.5 border border-[#E5E5E5] rounded-[6px] text-[14px] text-[#0D0D0D] focus:outline-none focus:ring-2 focus:ring-[#6366F1] resize-none"
                />
              </div>

              {/* Actions */}
              <div className="flex gap-3 pt-4">
                <button
                  onClick={onClose}
                  className="px-4 py-2.5 bg-white border border-[#E5E5E5] text-[#0D0D0D] rounded-[6px] text-[14px] font-medium hover:bg-[#FAFAFA] transition-colors"
                >
                  Cancel
                </button>
                <button
                  onClick={handleSchedule}
                  disabled={isScheduling || !candidateName.trim() || !candidateEmail.trim() || !startTime || !endTime}
                  className="flex-1 px-4 py-2.5 bg-[#6366F1] text-white rounded-[6px] text-[14px] font-medium hover:bg-[#4F46E5] transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                >
                  {isScheduling ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin" />
                      Scheduling...
                    </>
                  ) : (
                    <>
                      <CalendarIcon className="w-4 h-4" />
                      Schedule Meeting
                    </>
                  )}
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

